apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- resources/namespace.yaml
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.12.0
- resources/servicemonitor-argocd-server-metrics.yaml
- resources/servicemonitor-argocd-metrics.yaml
- resources/servicemonitor-argocd-repo-server-metrics.yaml

patches:
- path: patches/argocd-cm.yaml
- path: patches/argocd-server-deployment.yaml
- path: patches/argocd-repo-server-deployment.yaml
